version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:$CALIBRE_VERSION
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - $BASEPATH/app/data:/config
      - $BASEPATH/app/library:/books
    ports:
      - $CALIBRE_PORT:8083
    restart: unless-stopped
