version: "3"
services:
  db:
    image: docker.io/library/postgres:14
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - $BASEPATH/config/sql:/config/sql
      - $BASEPATH/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]

  app:
    image: quay.io/invidious/invidious:$INVIDIOUS_VERSION
    restart: always
    ports:
      - $INVIDIOUS_PORT:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: $POSTGRES_DB
          user: $POSTGRES_USER
          password: $POSTGRES_PASSWORD
          host: db
          port: 5432
        check_tables: true
        admins: [$ADMIN_USERNAME]
        popular_enabled: true
        hmac_key: $INVIDIOUS_HMAC_KEY
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - db

volumes:
  postgresdata:
