version: "3"

services:
  app:
    image: wallabag/wallabag:2.5.2
    env_file:
      - .env
    ports:
      - "8082:80"
    volumes:
      - ./app/images:/var/www/wallabag/web/assets/images
    restart: always
    depends_on:
      - db
      - cache
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s

  db:
    image: mariadb:10.9.4
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s

  cache:
    image: redis:alpine3.17
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
