version: "3"

services:
  db:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - $BASEPATH/db/data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s

  cache:
    image: redis:alpine3.17
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

  app:
    image: wallabag/wallabag:$WALLABAG_VERSION
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=$SYMFONY__ENV__DATABASE_DRIVER
      - SYMFONY__ENV__DATABASE_HOST=$SYMFONY__ENV__DATABASE_HOST
      - SYMFONY__ENV__DATABASE_PORT=$SYMFONY__ENV__DATABASE_PORT
      - SYMFONY__ENV__DATABASE_NAME=$SYMFONY__ENV__DATABASE_NAME
      - SYMFONY__ENV__DATABASE_USER=$SYMFONY__ENV__DATABASE_USER
      - SYMFONY__ENV__DATABASE_PASSWORD=$SYMFONY__ENV__DATABASE_PASSWORD
      - SYMFONY__ENV__DATABASE_CHARSET=$SYMFONY__ENV__DATABASE_CHARSET
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX=$SYMFONY__ENV__DATABASE_TABLE_PREFIX
      - SYMFONY__ENV__MAILER_HOST=$SYMFONY__ENV__MAILER_HOST
      - SYMFONY__ENV__MAILER_USER=$SYMFONY__ENV__MAILER_USER
      - SYMFONY__ENV__MAILER_PASSWORD=$SYMFONY__ENV__MAILER_PASSWORD
      - SYMFONY__ENV__FROM_EMAIL=$SYMFONY__ENV__FROM_EMAIL
      - SYMFONY__ENV__DOMAIN_NAME=$SYMFONY__ENV__DOMAIN_NAME
      - SYMFONY__ENV__SERVER_NAME=$SYMFONY__ENV__SERVER_NAME
      - SYMFONY__ENV__SECRET=$SYMFONY__ENV__SECRET
      - SYMFONY__ENV__LOCALE=$SYMFONY__ENV__LOCALE
    ports:
      - "8082:80"
    volumes:
      - $BASEPATH/app/images:/var/www/wallabag/web/assets/images
    restart: always
    depends_on:
      - db
      - cache
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s

